apiVersion: v1
kind: ConfigMap
metadata:
  name: guess-configmap
data:
  FLASK_APP: "run.py"
  FLASK_DB_TYPE: "postgres"
  FLASK_DB_NAME: "postgresdb"
  FLASK_DB_HOST: "postgres"
  FLASK_DB_PORT: "5432"